
INSERT INTO product_type (name, refrigerate, non_grocery, section)

VALUES
('Avocado',	false,	false,	1),
('Bananas',	false,	false,	1),
('Carrots',	false,	false,	1),
('Corn',	false,	false,	1),
('Cucumber',	false,	false,	1),
('Eggplant',	false,	false,	1),
('Garlic',	false,	false,	1),
('Juice',	false,	false,	1),
('Limes',	false,	false,	1),
('Onion',	false,	false,	1),
('Orange',	false,	false,	1),
('Potatoes',	false,	false,	1),
('Tempeh',	false,	false,	1),
('Tofu',	false,	false,	1),
('Tomato',	false,	false,	1),
('BBQ Sauce',	false,	false,	2),
('Lemon Juice',	false,	false,	2),
('Mustard',	false,	false,	2),
('Faykonaise',	true,	false,	2),
('Vinegar',	false,	false,	2),
('Dressing',	false,	false,	2),
('Ketchup',	false,	false,	2),
('Veggie Broth',	false,	false,	12),
('Bulgogi',	false,	false,	2),
('Salsa',	false,	false,	3),
('Soy Sauce',	false,	false,	3),
('Black Beans',	false,	false,	4),
('Olive Slices',	false,	false,	4),
('Bread',	false,	false,	5),
('Buns',	false,	false,	5),
('Bagel',	false,	false,	5),
('Chocolate Chips',	false,	false,	5),
('Wonder Flour Blue Canister',	null,	null,	5),
('Chickpeas',	false,	false,	6),
('Quinoa',	false,	false,	6),
('Rice',	false,	false,	6),
('Cereal',	false,	false,	7),
('Oatmeal',	false,	false,	7),
('Chips',	false,	false,	8),
('Mixed Nuts',	false,	false,	8),
('Body Wash',	false,	true,	10),
('Dish Detergent',	false,	true,	10),
('Deoderant',	false,	true,	10),
('Hand Soap',	false,	true,	10),
('Laundry Detergent',	false,	true,	10),
('Paper Towels',	false,	true,	10),
('Stickets',	false,	true,	10),
('Ziplock Bags',	false,	true,	10),
('Q-Tips',	false,	true,	10),
('Tooth Paste',	false,	true,	10),
('Garbage Bags',	false,	true,	10),
('Broccoli',	true,	false,	9),
('Ground Bits',	true,	false,	9),
('Patties',	true,	false,	9),
('Steam Bags',	true,	false,	9),
('Facon',	true,	false,	11),
('Slices of X',	true,	false,	11),
('Hummus',	true,	false,	11),
('BOOCHA',	true,	false,	11),
('Peanut Butter',	false,	false,	12),
('Jelly',	false,	false,	12),
('Snacks',	false,	false,	12),
('Pita Chips',	false,	false,	12),
('Protein Bar',	false,	false,	12),
('Almond Milk',	true,	false,	12),
('V-Cheese',	true,	false,	11),
('Burr',	true,	false,	12),
('Spinach',	true,	false,	1),
('Mushrooms',	true,	false,	1),
('Chocolate Milk',	true,	false,	12),
('Frozen Pizza',	true,	false,	9),
('Pretzels',	false,	false,	8),
('Sausage',	true,	false,	11),
('Hot Pocket',	true,	false,	9),
('Tortillas',	false,	false,	5),
('Aluminum Foil',	true,	true,	10),
('Squash',	true,	false,	1),
('Larabar',	false,	false,	8),
('Cream Cheese',	true,	false,	11),
('null',	null,	null,	null)
;